# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-p1:
resource "aws_subnet" "subnet-p1" {
  assign_ipv6_address_on_creation = false
  availability_zone               = var.availability_zone
  cidr_block                      = var.subnet_cidr
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "Private1"
    "kubernetes.io/cluster/${var.cluster-name}"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-p1"
  }
  vpc_id = var.vpc_id

  timeouts {}
}

resource "aws_route_table" "rtb_table_eks" {
  propagating_vgws = []
  route            = []
  tags = {
    "Name" = "eks-cluster/PrivateRouteTableEUWEST1A"

  }
  vpc_id = var.vpc_id
}

resource "aws_route_table_association" "rtb_table_eks_association" {
  route_table_id = aws_route_table.rtb_table_eks.id
  subnet_id      = aws_subnet.subnet-p1.id
}







