# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_vpc" "vpc_eks_cluster" {
  assign_generated_ipv6_cidr_block = false
  cidr_block                       = var.vpc_cidr
  enable_classiclink               = false
  enable_classiclink_dns_support   = false
  enable_dns_hostnames             = true
  enable_dns_support               = true
  instance_tenancy                 = "default"
  tags = {
    "Name" = "airflow_eks_cluster"
      }
}
